spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource

    druid:
      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 3000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
      aop-patterns: com.eternity.admin.*
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  jdbc:
    template:
      query-timeout: 3
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true